In [19]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
recommendation_matrix = pd.read_csv('recipe_ingr_matrix.csv', index_col=0)

In [42]:
recommendation_matrix.head()

3  5  7  8  9  11  12  13  14  15  ...  8011  8012  8014  8015  8016  \
id                                         ...                                 
312329  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
74301   0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
163861  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
289290  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
102015  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   

        8017  8018  8019  8020  8021  
id                                    
312329     0     0     0     0     0  
74301      0     0     0     0     0  
163861     0     0     0     0     0  
289290     0     0     0     0     0  
102015     0     0     0     0     0  

[5 rows x 6193 columns]

In [43]:
recommendation_matrix.shape

(79099, 6193)

In [44]:
recommendation_matrix.columns

Index(['3', '5', '7', '8', '9', '11', '12', '13', '14', '15',
       ...
       '8011', '8012', '8014', '8015', '8016', '8017', '8018', '8019', '8020',
       '8021'],
      dtype='object', length=6193)

In [45]:
recommendation_matrix.index

Index([312329,  74301, 163861, 289290, 102015, 120122, 239063,  69436, 347224,
       294925,
       ...
        78851, 430379,  82319,  48265, 316968, 158970, 420424,  16425,  34200,
        30618],
      dtype='int64', name='id', length=79099)

In [46]:
user_array = array = np.full(recommendation_matrix.shape[1], 0.5)

In [47]:
user_array.shape

(6193,)

In [48]:
user_array

array([0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5])

In [128]:
def select_best_recipe(recommendation_matrix, user_array, n=1):
    """
    compute the cosine similarity between the user array and the recipe array. retrieve the n best recipes
    Args:
        n (int, optional): Number of recipe to retrieve. Defaults to 1.

    Returns:
        recipe_index array(int): index of the best recipes (shape (1,n))
    """
    cos_sim = cosine_similarity([user_array], recommendation_matrix)
    sorted_indices = np.argsort(cos_sim[0])  # Access the first row of cos_sim
    n_best_indices = sorted_indices[-n:]
    return recommendation_matrix.iloc[n_best_indices]

In [129]:
best_indices = select_best_recipe(recommendation_matrix, user_array, n=5)

In [130]:
print(best_indices)

        3  5  7  8  9  11  12  13  14  15  ...  8011  8012  8014  8015  8016  \
id                                         ...                                 
73166   0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
211222  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
271926  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
318486  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
153465  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   

        8017  8018  8019  8020  8021  
id                                    
73166      0     0     0     0     0  
211222     0     0     0     0     0  
271926     0     0     0     0     0  
318486     0     0     0     0     0  
153465     0     0     0     0     0  

[5 rows x 6193 columns]


In [58]:
cos_sim[0][best_indices]

array([0.05682827, 0.05682827, 0.05682827, 0.05682827, 0.05682827])

In [60]:
cos_sim[0].max()

0.056828272961466794

In [62]:
recommendation_matrix.iloc[best_indices]

3  5  7  8  9  11  12  13  14  15  ...  8011  8012  8014  8015  8016  \
id                                         ...                                 
495352  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
34432   0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
464639  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
104086  0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   
92486   0  0  0  0  0   0   0   0   0   0  ...     0     0     0     0     0   

        8017  8018  8019  8020  8021  
id                                    
495352     0     0     0     0     0  
34432      0     0     0     0     0  
464639     0     0     0     0     0  
104086     0     0     0     0     0  
92486      0     0     0     0     0  

[5 rows x 6193 columns]

In [119]:
def update_vector_weight(user_vector, ingr_ids, increase=True):
    column_ids = [recommendation_matrix.columns.get_loc(col) for col in np.array(ingr_ids, dtype=str)]
    print(column_ids)
    for col_id in column_ids:
        if increase:
            boundary_diff = (1 - user_vector[col_id]) / 4
            user_vector[col_id] = min(1, user_vector[col_id] + boundary_diff)
        else:
            boundary_diff = user_vector[col_id] / 4
            user_vector[col_id] = max(0, user_vector[col_id] - boundary_diff)
    return user_vector

In [126]:
user_array_updated = update_vector_weight(user_array, [3,5,7,8,9], increase=True)

[0, 1, 2, 3, 4]


In [127]:
user_array_updated

array([0.65722656, 0.65722656, 0.65722656, ..., 0.5       , 0.5       ,
       0.5       ])